### ISSUE TITLE
Windows 8.1 Support

### ISSUE THREAD

**Issue by emiller1** [kirk-quinbar/HeartRateLE#8]
Hi, Will this app work with Windows 8.1 for WPF? I installed VS 2015 on a Windows 8.1 machine and I am missing several references in the project. If I add the Windows 10 packages will this still function correctly on Windows 8.1?

1>------ Build started: Project: HeartRateLE.Bluetooth, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Windows". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Windows.Foundation.FoundationContract". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Windows.Foundation.UniversalApiContract". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(8,15,8,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(9,15,9,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(10,15,10,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(11,15,11,23): error CS0234: The type or namespace name 'Security' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\PairingHelper.cs(6,15,6,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAEM\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\PairingHelper.cs(7,15,7,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\BluetoothAttribute.cs(2,15,2,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\DeviceSelectorInfo.cs(6,15,6,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(6,15,6,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(7,15,7,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(8,15,8,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Utilities.cs(6,15,6,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Utilities.cs(7,15,7,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Utilities.cs(8,15,8,23): error CS0234: The type or namespace name 'Security' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Utilities.cs(9,15,9,22): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(263,52,263,69): error CS0246: The type or namespace name 'BluetoothLEDevice' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(273,44,273,62): error CS0246: The type or namespace name 'GattCharacteristic' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(273,71,273,96): error CS0246: The type or namespace name 'GattValueChangedEventArgs' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\PairingHelper.cs(37,53,37,83): error CS0246: The type or namespace name 'DeviceInformationCustomPairing' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\PairingHelper.cs(37,92,37,123): error CS0246: The type or namespace name 'DevicePairingRequestedEventArgs' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(90,30,90,43): error CS0246: The type or namespace name 'DeviceWatcher' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(95,43,95,56): error CS0246: The type or namespace name 'DeviceWatcher' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(124,34,124,47): error CS0246: The type or namespace name 'DeviceWatcher' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(124,56,124,73): error CS0246: The type or namespace name 'DeviceInformation' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(150,36,150,49): error CS0246: The type or namespace name 'DeviceWatcher' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(150,58,150,81): error CS0246: The type or namespace name 'DeviceInformationUpdate' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(172,36,172,49): error CS0246: The type or namespace name 'DeviceWatcher' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(172,58,172,81): error CS0246: The type or namespace name 'DeviceInformationUpdate' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Utilities.cs(71,48,71,55): error CS0246: The type or namespace name 'IBuffer' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(17,17,17,34): error CS0246: The type or namespace name 'BluetoothLEDevice' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ENAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartDeviceWatcher.cs(25,17,25,30): error CS0246: The type or namespace name 'DeviceWatcher' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\HeartRateMonitor.cs(22,17,22,35): error CS0246: The type or namespace name 'GattCharacteristic' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\BluetoothAttribute.cs(16,35,16,52): error CS0246: The type or namespace name 'GattDeviceService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\BluetoothAttribute.cs(22,35,22,53): error CS0246: The type or namespace name 'GattCharacteristic' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\BluetoothAttribute.cs(11,16,11,34): error CS0246: The type or namespace name 'GattCharacteristic' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\BluetoothAttribute.cs(12,16,12,30): error CS0246: The type or namespace name 'GattDescriptor' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\BluetoothAttribute.cs(14,16,14,33): error CS0246: The type or namespace name 'GattDeviceService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ENAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\DeviceSelectorInfo.cs(24,16,24,27): error CS0246: The type or namespace name 'DeviceClass' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\NAME\Desktop\HeartRateLE-master\HeartRateLE-master\HeartRateLE.Bluetooth\Schema\DeviceSelectorInfo.cs(30,16,30,37): error CS0246: The type or namespace name 'DeviceInformationKind' could not be found (are you missing a using directive or an assembly reference?)

**Comment by kirk-quinbar** [comment]
no unfortunately windows 8.1 has horrible support for bluetooth LE and even in windows 10 until the june 2017 release. they finally added everything I needed to get this to work and fixed some bugs related to the firing of the events i needed to track the heart rate value. None of this api was available in windows 8.1 so there isnt a good way to support it for that OS.
